# Generated by Django 4.2.5 on 2023-12-17 17:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0004_alter_images_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Изображение'),
        ),
    ]
